defaults:
  - default
  - _self_

# algorithm
agent_type: "chai"

# checkpoint
checkpoint_path: '/nfs/kun2/users/yifei/llm_rl/twenty_questions_gpt2_model0_full.pt'
save_path: '/nfs/kun2/users/yifei/llm_rl/chai_20q_1'

# env
env_name: twenty_questions
env_load_path: '/nfs/kun2/users/yifei/llm_rl/20q_t5_oracle.pt'


# wandb logging
use_wandb: False
project_name: 'llm_rl_20q'
run_name: 'archer-acc'